Description of r_arc
r_arc
PURPOSE
R_ARC -
SYNOPSIS
function r_a = r_arc(e1,e2,r0,r)
DESCRIPTION
 R_ARC -
CROSS-REFERENCE INFORMATION
This function calls:
rot_around_v ROT_AROUND_V - matrix for rotation PHI radians around E_ROT
This function is called by:
etrp_scattering % Script illustrating (elastic) scattering
etrp_scattering2 % Script illustrating (elastic) scattering
SOURCE CODE
function r_a = r_arc(e1,e2,r0,r)
% R_ARC -
%
if nargin < 3 || isempty(r0)
  r0 = [0 0 0];
end
if nargin < 4 || isempty(r)
  r = 1;
end
e1 = e1/norm(e1);
e2 = e2/norm(e2);
e_to_rot_around = cross(e1,e2);
Theta = atan2(norm(cross(e1, e2)), dot(e1, e2));
n_points = round(Theta*180/pi)+1;
theta = linspace(0,Theta,n_points);
for i1 = n_points:-1:1,
  r_a(i1,:) = r0 + r*rot_around_v(e_to_rot_around,theta(i1))*e1';
end