Description of test_all
test_all
PURPOSE
TEST_ALL test the Factorize package (factorize, factorize1, and inverse)
SYNOPSIS
function test_all
DESCRIPTION
TEST_ALL test the Factorize package (factorize, factorize1, and inverse)
 If you have editted the Factorize package, type "clear classes" before
 running any tests.
 Example
   test_all
 See also factorize, factorize1, inverse, test_factorize,
 test_performance, test_accuracy, test_disp, test_errors
CROSS-REFERENCE INFORMATION
This function calls:
test_accuracy TEST_ACCURACY test the accuracy of the factorize object
test_all TEST_ALL test the Factorize package (factorize, factorize1, and inverse)
test_disp TEST_DISP test the display method of the factorize object
test_errors TEST_ERRORS tests error handling for the factorize object methods
test_performance TEST_PERFORMANCE compare performance of factorization/solve methods.
This function is called by:
test_all TEST_ALL test the Factorize package (factorize, factorize1, and inverse)
SOURCE CODE
function test_all
%TEST_ALL test the Factorize package (factorize, factorize1, and inverse)
%
% If you have editted the Factorize package, type "clear classes" before
% running any tests.
%
% Example
%   test_all
%
% See also factorize, factorize1, inverse, test_factorize,
% test_performance, test_accuracy, test_disp, test_errors
% Copyright 2009, Timothy A. Davis, University of Florida
help test_all
rand ('state', 0) ;         %#ok
test_disp ;                 % test disp(F)
test_errors ;               % test error handling for invalid matrices
err1 = test_accuracy ;      % test accuracy on a range of problems
err2 = test_performance ;   % performance tests
fprintf ('\nAll tests passed, maximum error OK: %g\n', max (err1, err2)) ;